### ISSUE TITLE
Oracle: Using of undefined variable causes connection close in editor window

### ISSUE THREAD

**Issue by mkyral** [tora-tool/tora#21] opened 2016-03-08 10:10 UTC
When I run select where I miss that there is some undefined variable, connection to Oracle is lost and I'm not able to re-run corrected select in the same editor window.

Steps to reproduce:
1) Connect to Oracle DBA
2) Execute command: `select * from dual where DUMMY = 'X';`
3) One row is selected.
4) Now change to: `select * from dual where DUMMY = undefined_variable;`
5) Execute the query
6) An error is returned. Note that connection was closed:

```
út bře 8 10:54:51 2016

ORA-00904: "UNDEFINED_VARIABLE": invalid identifier

error at SQL position 33 [1.34]:
select * from dual where DUMMY = undefined_variable
                                 ^

last SQL statement:
select * from dual where DUMMY = undefined_variable


út bře 8 10:54:51 2016

ORA-00904: "UNDEFINED_VARIABLE": invalid identifier


út bře 8 10:54:51 2016

ORA-03113: end-of-file on communication channel

error at SQL position 33 [1.34]:
select nvl2(dbms_transaction.local_transaction_id, 1, 0) from dual
                                 ^

last SQL statement:
select nvl2(dbms_transaction.local_transaction_id, 1, 0) from dual
```

7) Correct the query and re-run it

**Expected result**: Query is executed and value is shown.

**Current result**: An error is shown:

```
út bře 8 10:57:56 2016

ORA-03114: not connected to ORACLE

error at SQL position 0 [1.1]:
select * from dual where DUMMY = 'X'
^

last SQL statement:
select * from dual where DUMMY = 'X'


út bře 8 10:57:56 2016

ORA-01041: internal error. hostdef extension doesn't exist


út bře 8 10:57:56 2016

ORA-24338: statement handle not executed
```

I have to open a new editor window to get the result.
I expect that connection will be not closed due to this error, 

Tora compiled from GitHub sources: 07:40:16 4.3.2016
Gentoo linux, Qt 5.5.1, dev-db/oracle-instantclient-basic-10.2.0.3-r1 (because I still need to connect to some Oracle8i servers)
Tested on "Oracle Database 10g Enterprise Edition Release 10.2.0.5.0 - 64bit"

**Comment by mkyral** [comment] 2016-03-08 10:30
Just a note, this usally happen when I'm trying to execute some select from PL/SQL block.

**Comment by ibre5041** [comment] 2016-03-08 21:43
can you please check alert.log of the affected database? Tora implements some kind of critical exception sorter: https://github.com/tora-tool/tora/blob/master/extlibs/trotl/src/trotl_error.cpp#L47. The connection should be closed only iff some critical error occurred. Is it possible that the error raised ORA-7445 thus closing the connection from server side?

or maybe this is a culprit:
oerr ORA 01041
01041, 00000, "internal error. hostdef extension doesn't exist"
// *Cause: Pointer to hstdef extension in hstdef is null.
// *Action: Report as a bug

It looks like we're hitting some bug in InstantClient libs. Can you please to compile libporacle.so (or link) against libclntsh.so from "Oracle Database 10g Enterprise Edition Release 10.2.0.5.0 - 64bit"?

**Comment by mkyral** [comment] 2016-03-09 08:36
I'm just an developer, but finally I've found one database where I can read alert.log. There is nothing logged about this error. I've also tested the example in my local sqlplus instance - connection was not closed, all works as expected.

To compile with InstantClient I need more time, as there is no 10.2.0.5 ebuilds in Gentoo and Oracle changed naming schema completely, so I need to do more changes in ebuilds.

**Comment by mkyral** [comment] 2016-03-09 10:16
So I've installed 10.2.0.5.0 oracle client and recompiled Tora, but result is still the same.

**Comment by Cerh** [comment] 2016-05-17 07:34
12.1.0.2.0(oracle client), 11.2.0.4.0(instant client) result is still the same.
When I commented out the ORA-01041, the program hangs. Stack trace:
read
snttread
...
sql: select nvl2(dbms_transaction.local_transaction_id, 1, 0) from dual

**Comment by Cerh** [comment] 2016-05-17 08:52
Add to $ORACLE_HOME/network/admin/sqlnet.ora:
DISABLE_OOB = ON
Tested on oracle client 12.1.0.2.0 for linux
ORA-01041, ORA-03114, ORA-07445: USING THRID PARTY CONNECTION (Doc ID 1015065.102)

**Comment by ibre5041** [comment] 2016-05-17 09:33
Wow that's surprising.  OOB (out of bound data) is special attribute in TCP header. Oracle is only one application I'm aware of, that is using it. This is usually not a problem unless you either have paranoid security setup on your FW, or you use dumb VPN like OpenVPN. When wrapping TCP into TCP, this OOB flag in TCP header is discarded, then Oracle then reports various types of protocol violation errors. @mkyral do you connect to database via VPN? And if so, which one?

**Comment by Cerh** [comment] 2016-05-17 10:54
I have the same error, but I do not use VPN.
With this option, the program no longer hang when I connect to oracle using TNS.
select * from dualR -> ORA-00942: table or view does not exsist -> ... rethrow exception ...-> call select nvl2(dbms_transaction.local_transaction_id, 1, 0) from dual -> hangs on read()-snttread(). Oracle session wait SQL * Net break / reset to client event.

Linux 4.4.0-22,oracle client 12.1.0.2.0.

**Comment by ibre5041** [comment] 2016-05-18 12:47
I will try to reproduce it on Linux. Because this does not happen on Windows. Oracle documentation is not very clear in this case. OCIBreak sends OOB packet and this can leave Oracle connection in undefined state. So when this happens you should call OCIReset to re-sync. But it is not exactly written anywhere when you should call OCIReset.

**Comment by ibre5041** [comment] 2016-05-19 17:32
I still can not reproduce it. I tried it on Ubuntu (16.4) Linux. Using InstantClient 12c, and 11gR2 database running on localhost:

And I get:

> Thu May 19 19:27:15 2016
> trotl_stat.cpp:236	void trotl::SqlStatement::execute_describe()
> ORA-00904: "UNDEFINED_VARIABLE": invalid identifier
> 
> error at SQL position 33 [1.34]:
> select * from dual where DUMMY = undefined_variable
>                                  ^
> 
> last SQL statement:
> select * from dual where DUMMY = undefined_variable
> 
> 0x7f0b04a98af9: trotl::OciException::OciException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, trotl::SqlStatement&) in /home/ivan/.TOra3/poracle/libtrotl.so
> 0x7f0b04a98f1f: trotl::oci_check_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, trotl::SqlStatement&, int) in /home/ivan/.TOra3/poracle/libtrotl.so
> 0x7f0b04a90873: trotl::SqlStatement::execute_describe() in /home/ivan/.TOra3/poracle/libtrotl.so
> 0x7f0b04a8f543: trotl::SqlStatement::SqlStatement(trotl::OciConnection&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, int) in /home/ivan/.TOra3/poracle/libtrotl.so
> 0x7f0af82f77cf: oracleQuery::trotlQuery::trotlQuery(trotl::OciConnection&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, int) in /usr/local/lib64/tora-3.0/libporacle.so
> 0x7f0af82f4642: oracleQuery::execute() in /usr/local/lib64/tora-3.0/libporacle.so
> 0xa8ec1f: toEventQueryWorker::toQueryPriv::init() in ./src/tora
> 0xa8f4ae: toEventQueryWorker::init() in ./src/tora
> 0xa15365: uknown symbol in ./src/tora
> 0x7f0b2b3b9fca: QMetaObject::activate(QObject*, int, int, void**) in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
> 0x7f0b2b1aa835: uknown symbol in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
> 
> 
> Thu May 19 19:27:15 2016
> trotl_conn.cpp:82	void trotl::OciConnection::reset()
> ORA-00904: "UNDEFINED_VARIABLE": invalid identifier
> 
> 0x7f0b04a68b74: trotl::OciException::OciException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, OCIError*) in /home/ivan/.TOra3/poracle/libtrotl.so
> 0x7f0b04a4fe1e: trotl::oci_check_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, OCIError*, int) in /home/ivan/.TOra3/poracle/libtrotl.so
> 0x7f0b04a55785: trotl::OciConnection::reset() in /home/ivan/.TOra3/poracle/libtrotl.so
> 0x7f0af82ebb5a: toOracleConnectionSub::cancel() in /usr/local/lib64/tora-3.0/libporacle.so
> 0xa8c92b: toEventQuery::stop() in ./src/tora
> 0xb360f1: toResultModel::cleanup() in ./src/tora
> 0xb361a6: toResultModel::slotQueryError(toEventQuery*, toConnection::exception const&) in ./src/tora
> 0xa244da: uknown symbol in ./src/tora
> 0x7f0b2b3b9fca: QMetaObject::activate(QObject*, int, int, void**) in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
> 0xa14b0a: toEventQuery::error(toEventQuery*, toConnection::exception const&) in ./src/tora
> 0xa8d176: toEventQuery::slotError(toConnection::exception const&) in ./src/tora
> 0xa14319: uknown symbol in ./src/tora
> 0x7f0b2b3baea1: QObject::event(QEvent*) in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
> 0x7f0b2c60c05c: QApplicationPrivate::notify_helper(QObject*, QEvent*) in /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
> 

As you can see, error is reported twice once when statement is executed, 2nd when background query thread is being closed. And also reset is called. Please compile Tora in debug mode:
-DCMAKE_BUILD_TYPE=Debug, -DUSE_EXPERIMENTAL=ON

And post also stack traces.

**Comment by Cerh** [comment] 2016-05-20 08:00
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production ( IBM/AIX RISC System/6000), Client 12.1.0.2.0 on Ubuntu 16.04/ 64bit. 
I remove parameter DISABLE_OOB = ON and tora  is hangs
Stack trace from Eclipse:
tora Default [C/C++ Attach to Application]	
	tora [9855] [cores: 0,1,2,3]	
		Thread #1 [tora] 9855 [core: 1] (Suspended : User Request)	
			read() at syscall-template.S:84 0x7f29eb5cc9cd	
			snttread() at 0x7f29bab7f460	
			nttfprd() at 0x7f29bab7e8f5	
			nsbasic_brc() at 0x7f29bab73fb5	
			nsbrecv() at 0x7f29bab73db6	
			nioqrc() at 0x7f29bab69e4e	
			ttcdrv() at 0x7f29bab7fa2d	
			nioqwa() at 0x7f29bab6e959	
			upirtrc() at 0x7f29bab50a5c	
			kpurcsc() at 0x7f29bab5b276	
			kpuexec() at 0x7f29bab52352	
			OCIStmtExecute() at 0x7f29bab51409	
			trotl::SqlStatement::execute_internal() at trotl_stat.cpp:483 0x7f29b303617c	
			trotl::SqlStatement::pre_read_value() at trotl_stat.h:327 0x7f29b303a9c4	
			trotl::SqlStatement::operator>><int>() at trotl_stat.cpp:1 144 0x7f29b303a9c4	
			toOracleConnectionSub::hasTransaction() at tooracleconnection.cpp:370 0x7f29b2dc9611	
			toWorksheet::slotQueryDone() at toworksheet.cpp:1 578 0xf9e3b0	
			toWorksheet::qt_static_metacall() at moc_toworksheet.cpp:328 0xa2c512	
			QMetaObject::activate() at 0x7f29ec3f4fca	
			toResultTableView::done() at moc_toresulttableview.cpp:315 0xa2174f	
			toResultTableView::slotHandleDone() at toresulttableview.cpp:587 0xb37df3	
			toResultTableView::qt_static_metacall() at moc_toresulttableview.cpp:161 0xa2110a	
			QMetaObject::activate() at 0x7f29ec3f4fca	
			toResultModel::done() at moc_toresultmodel.cpp:198 0xa1ea29	
			toResultModel::cleanup() at toresultmodel.cpp:163 0xb1e077	
			toResultModel::slotQueryError() at toresultmodel.cpp:175 0xb1e0e8	
			toResultModel::qt_static_metacall() at moc_toresultmodel.cpp:114 0xa1e774	
			QMetaObject::activate() at 0x7f29ec3f4fca	
			toEventQuery::error() at moc_toeventquery.cpp:346 0xa12a6e	
			toEventQuery::slotError() at toeventquery.cpp:295 0xa7a300	
			toEventQuery::qt_static_metacall() at moc_toeventquery.cpp:146 0xa1227d	
			QObject::event() at 0x7f29ec3f5ea1	
			QApplicationPrivate::notify_helper() at 0x7f29ed43705c	
			QApplication::notify() at 0x7f29ed43c516	
			QCoreApplication::notifyInternal() at 0x7f29ec3c662b	
			QCoreApplicationPrivate::sendPostedEvents() at 0x7f29ec3c8a26	
			0x7f29ec41c673	
			g_main_context_dispatch() at 0x7f29ea964127	
			0x7f29ea964380	
			g_main_context_iteration() at 0x7f29ea96442c	
			<...more frames...>	
		Thread #2 [toEventQuery] 9879 [core: 3] (Suspended : Container)	
			poll() at syscall-template.S:84 0x7f29eb5d0e8d	
			0x7f29ea96431c	
			g_main_context_iteration() at 0x7f29ea96442c	
			QEventDispatcherGlib::processEvents() at 0x7f29ec41ca9b	
			QEventLoop::exec() at 0x7f29ec3c3dea	
			QThread::exec() at 0x7f29ec1e08a4	
			BGThread::run() at toeventqueryworker.h:77 0xa1390a	
			0x7f29ec1e584e	
			start_thread() at pthread_create.c:333 0x7f29eb2c06fa	
			clone() at clone.S:109 0x7f29eb5dcb5d	
		Thread #3 [logWriterOwnThr] 9873 [core: 0] (Suspended : Container)	
		Thread #4 [logWriterOwnThr] 9872 [core: 0] (Suspended : Container)	
		Thread #5 [ParserThread] 9871 [core: 0] (Suspended : Container)	
		Thread #6 [logWriterOwnThr] 9869 [core: 0] (Suspended : Container)	
		Thread #7 [toCacheWorker t] 9868 [core: 0] (Suspended : Container)	
		Thread #8 [logWriterOwnThr] 9867 [core: 0] (Suspended : Container)	
		Thread #9 [logWriterOwnThr] 9866 [core: 0] (Suspended : Container)	
		Thread #10 [logWriterOwnThr] 9863 [core: 0] (Suspended : Container)	
		Thread #11 [dconf worker] 9859 [core: 0] (Suspended : Container)	
		Thread #12 [gdbus] 9858 [core: 3] (Suspended : Container)	
		Thread #13 [gmain] 9857 [core: 0] (Suspended : Container)	
		Thread #14 [QXcbEventReader] 9856 [core: 2] (Suspended : Container)	
	gdb (7.11)	

With  -DUSE_EXPERIMENTAL=ON is not compiled:
-parsing/tsqllexerpostgresql.cc multiple definition of reMySQLLexStatement -> MySQL?
Util::RegisterInFactory<SQLLexer::postgreSQLGuiLexer, LexerFactTwoParmSing> reMySQLLexStatement("PostreSQLGuiLexer");

-editor/tosqltext.cpp; need append
#include <QToolTip>

**Comment by ibre5041** [comment] 2016-05-20 16:03
That stacktrace looks perfectly Ok. It looks like the thread simply waits for database response. Can you check session's wait event in v$session? Is there something like "SQLNET message from/to client" ?
Maybe try to add DIAG_SIGHANDLER_ENABLED=FALSE into sqlnet.ora. 
Does this hanging occur also on other databases? Local XE instance for example?

**Comment by ibre5041** [comment] 2016-07-06 07:07
Ping. Any news about this?

**Comment by ibre5041** [comment] 2017-07-21 22:14
no response

**Closed by ibre5041** 2017-07-21 22:14 UTC
